language: c
cache: ccache

before_install:
  - pwd
  - sudo mkdir -p -m 0755 /var/empty

addons:
  apt:
    update: true
    packages:
    - autoconf
    - automake
    - libtool
    - libssl-dev
    - make
    - unzip
    - xsltproc

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
    addons:
      apt:
        packages:
        - gcc
  - os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        sources:
        - gcc
  - os: osx
    compiler: clang
    install:
    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    addons:
      homebrew:
        packages:
        - doxygen
        - ccache
        update: false
    env:
      - ARCH=x64
      - CC_OVERRIDE=clang

script:
  - pwd
  - echo "Using GGC  version:"
  - gcc --version
  - echo Running openssh-portable integration tests...
  - cd integration/oqs_openssh
  - OPENSSH_LOG_PATH=`date "+%Y%m%d-%Hh%Mm%Ss-openssh.log.txt"`
  - time ./run.sh | tee $OPENSSH_LOG_PATH
  - echo
  - echo ls *log.txt
  - echo
  - echo "Last 100 lines of the SSH build logs:"
  - tail -n 100 $OPENSSH_LOG_PATH
  - cd ..
  - echo
  - echo Running openssl integration tests...
  - cd oqs_openssl
  - OPENSSL_LOG_PATH=`date "+%Y%m%d-%Hh%Mm%Ss-openssl.log.txt"`
  - time ./run.sh | tee $OPENSSL_LOG_PATH
  - echo
  - echo ls *log.txt
  - echo
  - echo "Last 100 lines of the SSL build logs:"
  - tail -n 100 $OPENSSL_LOG_PATH
