language: c

before_install:
  - pwd
  - sudo mkdir -p -m 0755 /var/empty
  - lsb_release -a 2>/dev/null | grep -q "14.04"
  - IS_V14=$?
  - if [ $IS_V14 ]
  - then
  -   echo "Found Ubuntu 14.04"
  -   sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  -   sudo apt update
  -   sudo apt install gcc-5
  - else
  -   echo "Another Ubuntu version found"
  - fi

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
    addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - autoconf
        - automake
        - gcc
        - libtool
        - libssl-dev
        - make
        - unzip
        - xsltproc
  - os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - autoconf
        - automake
        - gcc
        - libtool
        - libssl-dev
        - make
        - unzip
        - xsltproc
  - os: osx
    compiler: clang
    before_install:
      - brew install doxygen
    env:
      - ARCH=x64
      - CC_OVERRIDE=clang

script:
  - pwd
  - echo Running openssh-portable integration tests...
  - cd integration/oqs_openssh
  - ./run.sh | tee `date "+%Y%m%d-%Hh%Mm%Ss-openssh.log.txt"`
  - cd ..
  - echo
  - echo Running openssl integration tests...
  - cd oqs_openssl
  - ./run.sh | tee `date "+%Y%m%d-%Hh%Mm%Ss-openssl.log.txt"`
